version: '1.0'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=Tasks

    networks:
      - java-backend-network

  spring_app:
    container_name: spring_app
    image: sprig_app
    build:
      context: .
      dockerfile: dockerfile
      args:
        - JARFILE=./api/build/libs/api-1.0-SNAPSHOT.jar
    ports:
      -"8080:8080"
    networks:
      - java-backend-network
    depends_on:
      - mysql

networks:
  java-backend-network:
    driver: bridge