openapi: 3.0.0
info:
  title: Tasks Service
  description: task service
  version: 1.0

servers:
  - url: http://localhost:8080
    description: Local server


components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer

security:
  - bearer: []

paths:
  /tasks:
    $ref: 'TaskRequest.yaml#/tasks'
  /tasks/{task_id}:
    $ref: 'TaskRequest.yaml#/task'
