openapi: 3.0.0
info:
  title: Corgis service
  description: Corgis service
  version: 1.0

servers:
  - url: http://localhost:8082
    description: Local server for debugging

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer

security:
  - bearer: []

paths:
  /corgis:
    $ref: 'corgisRequests.yaml#/corgis'
  /corgis/{corgi_id}:
    $ref: 'corgisRequests.yaml#/corgi'
  /corgis_async:
    $ref: 'corgisRequests.yaml#/corgis_async'